bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post6
rdf_sha256: f7d7f75373682a233a670d00ca1b91fd4d9ab959c61a7de36be1355850f501a6
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post6
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre., tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''content'':
        [''cells'', ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'',
        ''mitochondria'', ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']},
        {''task'': [''semantic-segmentation'', ''instance-segmentation'', ''object-detection'',
        ''image-classification'', ''denoising'', ''image-restoration'', ''image-reconstruction'',
        ''in-silico-labeling'']}]'}
  - bioimageio_spec_version: 0.4.5post6
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre., tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''content'':
        [''cells'', ''nuclei'', ''extracellular-vesicles'', ''tissue'', ''plant'',
        ''mitochondria'', ''vasculature'', ''cell-membrane'', ''brain'', ''whole-organism'']},
        {''task'': [''semantic-segmentation'', ''instance-segmentation'', ''object-detection'',
        ''image-classification'', ''denoising'', ''image-restoration'', ''image-reconstruction'',
        ''in-silico-labeling'']}]'}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post6, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  ilastik:
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: No module named 'tensorflow'
    name: reproduce test outputs with ilastik <todo version> (draft) using keras_hdf5
      weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\",
        line 147, in test_resource\n    with create_prediction_pipeline(\n", "  File
        \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 195, in create_prediction_pipeline\n    model_adapter: ModelAdapter =
        create_model_adapter(\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 154, in _get_model_adapter\n    from ._tensorflow_model_adapter import
        KerasModelAdapter\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\",
        line 6, in <module>\n    import tensorflow as tf\n"]
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: No module named 'tensorflow'
    name: reproduce test outputs with ilastik <todo version> (draft) using tensorflow_saved_model_bundle
      weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\",
        line 147, in test_resource\n    with create_prediction_pipeline(\n", "  File
        \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 195, in create_prediction_pipeline\n    model_adapter: ModelAdapter =
        create_model_adapter(\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 133, in _get_model_adapter\n    from ._tensorflow_model_adapter import
        TensorflowModelAdapter\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\",
        line 6, in <module>\n    import tensorflow as tf\n"]
