bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.8.post1
rdf_sha256: 18989afc876b5c977a56adc3158f89031dd485991a20e93b06e34198c2b7bf6a
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - error: No module named 'tqdm'
    name: import test_resource from test environment
    status: failed
    traceback: ["  File \"/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py\",
        line 41, in main\n    from bioimageio.core.resource_tests import test_resource\n",
      "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.10/site-packages/bioimageio/core/__init__.py\",
        line 13, in <module>\n    from .prediction_pipeline import create_prediction_pipeline\n",
      "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/__init__.py\",
        line 2, in <module>\n    from ._prediction_pipeline import PredictionPipeline,
        create_prediction_pipeline\n", "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 12, in <module>\n    from ._stat_state import StatsState\n", "  File
        \"/home/runner/micromamba-root/envs/6406757/lib/python3.10/site-packages/bioimageio/core/prediction_pipeline/_stat_state.py\",
        line 3, in <module>\n    from tqdm import tqdm\n"]
  - error: No module named 'tqdm'
    name: import test_resource from test environment
    status: failed
    traceback: ["  File \"/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py\",
        line 41, in main\n    from bioimageio.core.resource_tests import test_resource\n",
      "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.9/site-packages/bioimageio/core/__init__.py\",
        line 13, in <module>\n    from .prediction_pipeline import create_prediction_pipeline\n",
      "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/__init__.py\",
        line 2, in <module>\n    from ._prediction_pipeline import PredictionPipeline,
        create_prediction_pipeline\n", "  File \"/home/runner/micromamba-root/envs/6406757/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 12, in <module>\n    from ._stat_state import StatsState\n", "  File
        \"/home/runner/micromamba-root/envs/6406757/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_stat_state.py\",
        line 3, in <module>\n    from tqdm import tqdm\n"]
  deepimagej: []
  ilastik:
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post6, error: null,
    name: reproduce test outputs with ilastik 1.4.0b27 using torchscript weights,
    reason: null, status: passed, traceback: null}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post6, error: null,
    name: reproduce test outputs with ilastik 1.4.0b27 using pytorch_state_dict weights,
    reason: null, status: passed, traceback: null}
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik 1.4.0b26 using torchscript weights,
    reason: null, status: passed, traceback: null}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6406756/6406757, name: reproduce
      test outputs with ilastik 1.4.0b27, reason: error, status: failed}
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik 1.4.0b26 using pytorch_state_dict weights,
    reason: null, status: passed, traceback: null}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6406756/6406757, name: reproduce
      test outputs with ilastik 1.4.0b26, reason: error, status: failed}
