{
  "bio-core-mix": {
    "py3.8.12_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format onnx not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.8.12_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "HTTP Error 500: INTERNAL SERVER ERROR",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\", line 135, in load_resource_description\n    raw_rd = load_raw_resource_description(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\", line 111, in load_raw_resource_description\n    raw_rd = spec.load_raw_resource_description(source, update_to_current_format=True)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 213, in load_raw_resource_description\n    data, source_name, root, type_ = resolve_rdf_source_and_type(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 155, in resolve_rdf_source_and_type\n    data, source_name, root = resolve_rdf_source(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 113, in resolve_rdf_source\n    source, resp = urlretrieve(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 247, in urlretrieve\n    with contextlib.closing(urlopen(url, data)) as fp:\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 531, in open\n    response = meth(req, response)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 640, in http_response\n    response = self.parent.error(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 569, in error\n    return self._call_chain(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n    result = func(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/urllib/request.py\", line 649, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n"
        ]
      }
    ],
    "py3.8.12_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_state_dict not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.8.12_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "module 'tensorflow._api.v2.saved_model' has no attribute 'tag_constants'",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 60, in test_resource\n    results = predict(prediction_pipeline, inputs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction.py\", line 250, in predict\n    return prediction_pipeline.forward(*tagged_data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 91, in forward\n    prediction = self.predict(*preprocessed)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 86, in predict\n    return self._model.forward(*input_tensors)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 93, in forward\n    result = self._forward_tf(*data)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\", line 56, in _forward_tf\n    tag = tf.saved_model.tag_constants.SERVING\n"
        ]
      }
    ],
    "py3.9.7_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format onnx not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Failed to download https://sandbox.zenodo.org/api/files/b7b70fb7-b859-479b-a30e-3d5ad4463929/binarize.ijm (HTTP Error 500: INTERNAL SERVER ERROR)",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\", line 145, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd, nodes_module=nodes)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 287, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path).transform(raw_rd)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 57, in transform_dict\n    return {key: self.transform(value) for key, value in node.items()}\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 57, in <dictcomp>\n    return {key: self.transform(value) for key, value in node.items()}\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 54, in transform_list\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 54, in <listcomp>\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 56, in transform_URI\n    local_path = resolve_uri(node, root_path=self.root_path)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/functools.py\", line 877, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 150, in _resolve_uri_uri_node\n    local_path = _download_uri_to_local_path(path_or_remote_uri)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 280, in _download_uri_to_local_path\n    raise RuntimeError(f\"Failed to download {uri} ({e})\")\n"
        ]
      }
    ],
    "py3.9.7_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format pytorch_state_dict not among weight formats listed in model: ['tensorflow_saved_model_bundle', 'keras_hdf5']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Failed to download https://sandbox.zenodo.org/api/files/b7b70fb7-b859-479b-a30e-3d5ad4463929/exampleImage.tif (HTTP Error 500: INTERNAL SERVER ERROR)",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\", line 145, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd, nodes_module=nodes)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 287, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path).transform(raw_rd)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 57, in transform_dict\n    return {key: self.transform(value) for key, value in node.items()}\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 57, in <dictcomp>\n    return {key: self.transform(value) for key, value in node.items()}\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 54, in transform_list\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 54, in <listcomp>\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 56, in transform_URI\n    local_path = resolve_uri(node, root_path=self.root_path)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/functools.py\", line 877, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 150, in _resolve_uri_uri_node\n    local_path = _download_uri_to_local_path(path_or_remote_uri)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 280, in _download_uri_to_local_path\n    raise RuntimeError(f\"Failed to download {uri} ({e})\")\n"
        ]
      }
    ]
  }
}