{
  "bio-core-mix": {
    "py3.8.12_onnx": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.8.12_pytorch_script": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.8.12_pytorch_state_dict": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.8.12_tensorflow_saved_model_bundle": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_onnx": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_pytorch_script": [
      {
        "error": "expected loaded resource to be a dictionary, but got type <class 'str'>: https://sandbox.zenodo.org/api/files/9335cedd-0a6f-458d-a28e-ac4a79216e2e/rdf.yaml",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 41, in validate\n    rdf_source, source_name, root = resolve_rdf_source(rdf_source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 113, in resolve_rdf_source\n    source, resp = urlretrieve(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 239, in urlretrieve\n    with contextlib.closing(urlopen(url, data)) as fp:\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 523, in open\n    response = meth(req, response)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 632, in http_response\n    response = self.parent.error(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 561, in error\n    return self._call_chain(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_pytorch_state_dict": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_tensorflow_saved_model_bundle": [
      {
        "error": "Invalid RDF type dataset",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 56, in validate\n    raw_rd = load_raw_resource_description(rdf_source, update_to_current_format=update_format)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 217, in load_raw_resource_description\n    sub_spec = _get_spec_submodule(type_, data_version)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 187, in _get_spec_submodule\n    sub_spec = get_latest_format_version_module(type_)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/common.py\", line 54, in get_latest_format_version_module\n    raise ValueError(f\"Invalid RDF type {type_}\")\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ]
  }
}