{
  "bio-core-mix": {
    "py3.8.12_onnx": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Failed to download https://sandbox.zenodo.org/api/files/36604653-1541-4891-b6bd-de5963217e5f/environment.yaml (HTTP Error 500: INTERNAL SERVER ERROR)",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\", line 145, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd, nodes_module=nodes)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 287, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path).transform(raw_rd)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 56, in transform_URI\n    local_path = resolve_uri(node, root_path=self.root_path)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/functools.py\", line 875, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 150, in _resolve_uri_uri_node\n    local_path = _download_uri_to_local_path(path_or_remote_uri)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 280, in _download_uri_to_local_path\n    raise RuntimeError(f\"Failed to download {uri} ({e})\")\n"
        ]
      }
    ],
    "py3.8.12_pytorch_script": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Failed to download https://sandbox.zenodo.org/api/files/36604653-1541-4891-b6bd-de5963217e5f/raw.png (HTTP Error 429: TOO MANY REQUESTS)",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\", line 145, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd, nodes_module=nodes)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 287, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path).transform(raw_rd)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 54, in transform_list\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 54, in <listcomp>\n    return [self.transform(subnode) for subnode in node]\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 56, in transform_URI\n    local_path = resolve_uri(node, root_path=self.root_path)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/functools.py\", line 875, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 150, in _resolve_uri_uri_node\n    local_path = _download_uri_to_local_path(path_or_remote_uri)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\", line 280, in _download_uri_to_local_path\n    raise RuntimeError(f\"Failed to download {uri} ({e})\")\n"
        ]
      }
    ],
    "py3.8.12_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "different number of dimensions on data and dims: 1 vs 5",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 60, in test_resource\n    results = predict(prediction_pipeline, inputs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction.py\", line 247, in predict\n    tagged_data = [\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction.py\", line 248, in <listcomp>\n    xr.DataArray(ipt, dims=ipt_spec.axes) for ipt, ipt_spec in zip(inputs, prediction_pipeline.input_specs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/xarray/core/dataarray.py\", line 410, in __init__\n    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/xarray/core/dataarray.py\", line 127, in _infer_coords_and_dims\n    raise ValueError(\n"
        ]
      }
    ],
    "py3.8.12_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "weight format tensorflow_saved_model_bundle not among weight formats listed in model: ['pytorch_state_dict']",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\", line 56, in test_resource\n    prediction_pipeline = create_prediction_pipeline(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\", line 142, in create_prediction_pipeline\n    model_adapter: ModelAdapter = create_model_adapter(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\", line 61, in create_model_adapter\n    raise RuntimeError(\n"
        ]
      }
    ],
    "py3.9.7_onnx": [
      {
        "error": "expected loaded resource to be a dictionary, but got type <class 'str'>: https://sandbox.zenodo.org/api/files/36604653-1541-4891-b6bd-de5963217e5f/rdf.yaml",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 41, in validate\n    rdf_source, source_name, root = resolve_rdf_source(rdf_source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 113, in resolve_rdf_source\n    source, resp = urlretrieve(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 239, in urlretrieve\n    with contextlib.closing(urlopen(url, data)) as fp:\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 523, in open\n    response = meth(req, response)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 632, in http_response\n    response = self.parent.error(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 561, in error\n    return self._call_chain(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_pytorch_script": [
      {
        "error": "expected loaded resource to be a dictionary, but got type <class 'str'>: https://sandbox.zenodo.org/api/files/36604653-1541-4891-b6bd-de5963217e5f/rdf.yaml",
        "name": "static resource format validation",
        "nested_errors": {},
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/commands.py\", line 41, in validate\n    rdf_source, source_name, root = resolve_rdf_source(rdf_source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/io_.py\", line 113, in resolve_rdf_source\n    source, resp = urlretrieve(source)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 239, in urlretrieve\n    with contextlib.closing(urlopen(url, data)) as fp:\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 214, in urlopen\n    return opener.open(url, data, timeout)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 523, in open\n    response = meth(req, response)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 632, in http_response\n    response = self.parent.error(\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 561, in error\n    return self._call_chain(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 494, in _call_chain\n    result = func(*args)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/urllib/request.py\", line 641, in http_error_default\n    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n"
        ]
      },
      {
        "error": "skipped due to invalid resource format",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": null
      }
    ],
    "py3.9.7_pytorch_state_dict": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "different number of dimensions on data and dims: 1 vs 5",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 60, in test_resource\n    results = predict(prediction_pipeline, inputs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction.py\", line 247, in predict\n    tagged_data = [\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/prediction.py\", line 248, in <listcomp>\n    xr.DataArray(ipt, dims=ipt_spec.axes) for ipt, ipt_spec in zip(inputs, prediction_pipeline.input_specs)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/xarray/core/dataarray.py\", line 410, in __init__\n    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/xarray/core/dataarray.py\", line 127, in _infer_coords_and_dims\n    raise ValueError(\n"
        ]
      }
    ],
    "py3.9.7_tensorflow_saved_model_bundle": [
      {
        "name": "static resource format validation",
        "success": true
      },
      {
        "error": "Failed to download https://sandbox.zenodo.org/api/files/36604653-1541-4891-b6bd-de5963217e5f/unet.py (HTTP Error 429: TOO MANY REQUESTS)",
        "name": "reproduced test outputs",
        "success": false,
        "traceback": [
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\", line 49, in test_resource\n    model = load_resource_description(model_rdf)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\", line 145, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd, nodes_module=nodes)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 287, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path).transform(raw_rd)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in generic_transformer\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 63, in <dictcomp>\n    return dataclasses.replace(node, **{name: self.transform(value) for name, value in iter_fields(node)})\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/spec/shared/utils.py\", line 48, in transform\n    return transformer(node)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 63, in transform_ImportableSourceFile\n    source_file=resolve_uri(node.source_file, self.root_path), callable_name=node.callable_name\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/functools.py\", line 877, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 150, in _resolve_uri_uri_node\n    local_path = _download_uri_to_local_path(path_or_remote_uri)\n",
          "  File \"/usr/share/miniconda/envs/bio-spec/lib/python3.9/site-packages/bioimageio/core/resource_io/utils.py\", line 280, in _download_uri_to_local_path\n    raise RuntimeError(f\"Failed to download {uri} ({e})\")\n"
        ]
      }
    ]
  }
}