bioimageio_spec_version: 0.4.8.post1
rdf_sha256: 850fbf740fa544626904c6907f58cd0b651afded050efe1f66a6fbde21c16442
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'', ''resnet'',
        ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'', ''instance-segmentation'',
        ''object-detection'', ''image-classification'', ''denoising'', ''image-restoration'',
        ''image-reconstruction'', ''in-silico-labeling'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.3.6
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'', ''resnet'',
        ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'', ''instance-segmentation'',
        ''object-detection'', ''image-classification'', ''denoising'', ''image-restoration'',
        ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - error: No module named 'tqdm'
    name: import test_resource from test environment
    status: failed
    traceback: ["  File \"/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py\",
        line 41, in main\n    from bioimageio.core.resource_tests import test_resource\n",
      "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.11/site-packages/bioimageio/core/__init__.py\",
        line 13, in <module>\n    from .prediction_pipeline import create_prediction_pipeline\n",
      "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.11/site-packages/bioimageio/core/prediction_pipeline/__init__.py\",
        line 2, in <module>\n    from ._prediction_pipeline import PredictionPipeline,
        create_prediction_pipeline\n", "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.11/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 12, in <module>\n    from ._stat_state import StatsState\n", "  File
        \"/home/runner/micromamba-root/envs/6539073/lib/python3.11/site-packages/bioimageio/core/prediction_pipeline/_stat_state.py\",
        line 3, in <module>\n    from tqdm import tqdm\n"]
  - error: No module named 'tqdm'
    name: import test_resource from test environment
    status: failed
    traceback: ["  File \"/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py\",
        line 41, in main\n    from bioimageio.core.resource_tests import test_resource\n",
      "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.9/site-packages/bioimageio/core/__init__.py\",
        line 13, in <module>\n    from .prediction_pipeline import create_prediction_pipeline\n",
      "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/__init__.py\",
        line 2, in <module>\n    from ._prediction_pipeline import PredictionPipeline,
        create_prediction_pipeline\n", "  File \"/home/runner/micromamba-root/envs/6539073/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 12, in <module>\n    from ._stat_state import StatsState\n", "  File
        \"/home/runner/micromamba-root/envs/6539073/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_stat_state.py\",
        line 3, in <module>\n    from tqdm import tqdm\n"]
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, error: rdf does not have a compatible weight
      format, name: Initial compatibility checks with DeepImageJ, status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.1
    bioimageio_spec_version: 0.4.5post3
    error: No module named 'onnxruntime'
    name: reproduce test outputs with ilastik 1.4.0b26 using onnx weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 159, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 138, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: Not found any of the specified weights formats ['pytorch_script']
    name: reproduce test outputs with ilastik 1.4.0b27 using pytorch_script weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 55, in load_resource_description\n    raise ValueError(f\"Not found any
        of the specified weights formats {weights_priority_order}\")\n"]
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: No module named 'onnxruntime'
    name: reproduce test outputs with ilastik 1.4.0b27 using onnx weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 196, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 138, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
  - bioimageio_core_version: 0.5.1
    bioimageio_spec_version: 0.4.5post3
    error: Not found any of the specified weights formats ['pytorch_script']
    name: reproduce test outputs with ilastik 1.4.0b26 using pytorch_script weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 49, in load_resource_description\n    raise ValueError(f\"Not found any
        of the specified weights formats {weights_priority_order}\")\n"]
